version: '3.6'

services:
  fedora:
    image: samvera/fcrepo4:4.7.5
    ports:
      - 8984:8080
    volumes:
      - /data/fcrepo_data:/data
    environment:
      JAVA_OPTIONS: '-Xmx512m'

  solr:
    image: solr:8.7
    ports:
      - 8983:8983
    volumes:
      - /data/solr_data:/var/solr:cached
      - ./solr/conf:/opt/solr/server/configsets/hyraxconf
